---
title: "qc-summary"
author: Linda Nguyen
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 5
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: sandstone
  pdf_document:
    toc: true
    toc_depth: 5
    number_sections: true
    df_print: kable
params:
  chapter_name: "chapter4_scRNA-seq" # edit manually
knit: |
  (function(inputFile, encoding) {
    library(rmarkdown)
    # Read the YAML parameters into 'yaml_params' to avoid conflicts
    yaml_params <- rmarkdown::yaml_front_matter(inputFile)$params
    expt_name <- yaml_params$expt_name
    analysis_date <- format(Sys.Date(), "%Y-%m-%d")

    # Output formats to render
    formats <- c("html_document", "pdf_document")
    
    # Corresponding output file extensions
    extensions <- c(".html", ".pdf")
    
    # Render to each format
    for (i in seq_along(formats)) {
      output_file <- paste0(
        "qc-summary", # edit manually
        "_", analysis_date, extensions[i]
      )
      rmarkdown::render(
        input = inputFile, encoding = encoding,
        params = yaml_params,
        output_format = formats[i],
        output_file = output_file)
    }
  })
---

# Introduction

This script creates figures for the PhD chapter **`r params$chapter_nr`**.

This script:

* creates a grouped bar chart for quality control exclusion criteria


# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load utilities.

```{r load utilities, echo=TRUE, message=FALSE}
# load utilities
source("../utils/packages.R")
source("../utils/fonts.R")
source("../utils/setup.R")
source("../utils/theme_thesis.R")
source("../utils/colours.R")

# setup packages and fonts
load_thesis_packages()
setup_latex_fonts()

# setup paths and knitr options
dir.out <- setup_output_dir(params$chapter_name)
setup_knitr_opts(dir.out)
```


# Preparation

Create the data frame.

```{r create the data frame}
qc_data <- data.frame(
  Sample = c(
    "P13 WT1", "P13 MUT1",
    "P13 WT2", "P13 MUT2",
    "P13 WT3", "P13 MUT3",
    "P18 WT1", "P18 MUT1",
    "P18 WT2", "P18 MUT2",
    "P18 WT3", "P18 MUT3"
  ),
  
  UMI_High = c(
    11.9, 24.8, 14.7, 3.2, 34.7, 11.8,
    6.9, 10.0, 3.6, 12.8, 0.7, 0.1
  ),
  
  UMI_Low = c(
    37.9, 3.1, 30.4, 79.5, 19.7, 38.9,
    31.4, 30.0, 40.7, 26.5, 88.3, 98.4
  ),
  
  Genes_Low = c(
    43.2, 11.9, 28.1, 78.4, 21.5, 36.1,
    30.7, 29.0, 36.8, 26.2, 86.6, 97.5
  ),
  
  Mito_High = c(
    0.3, 0.2, 2.4, 1.7, 3.1, 6.2,
    23.8, 18.4, 14.2, 19.2, 37.4, 41.6
  ),
  
  Haemo_High = c(
    4.1, 7.7, 0.3, 0.5, 5.7, 0.5,
    0.0, 0.2, 0.2, 0.4, 0.1, 31.0
  )
)

qc_data
```

Convert to long format for ggplot.

```{r convert to long format}
qc_long <- qc_data %>%
  pivot_longer(
    cols = -Sample,
    names_to = "Exclusion_Type",
    values_to = "Percentage"
  ) %>%
  mutate(
    # create factor for proper ordering
    Sample = factor(Sample, levels = c(
      "P13 WT1", "P13 MUT1",
      "P13 WT2", "P13 MUT2",
      "P13 WT3", "P13 MUT3",
      "P18 WT1", "P18 MUT1",
      "P18 WT2", "P18 MUT2",
      "P18 WT3", "P18 MUT3"
    )),
    
    # clean up exclusion type names
    Exclusion_Type = factor(
      Exclusion_Type,
      levels = c(
        "UMI_High", "UMI_Low", "Genes_Low", "Mito_High", "Haemo_High"
      ),
      labels = c("UMI↑", "UMI↓", "Genes↓", "Mito↑", "Haemo↑")
    )
  )

head(qc_long)
```


# Bar chart

Create grouped bar chart.

```{r bar_qc_latex, fig.width=6, fig.height=4}
p <- ggplot(qc_long, aes(x = Sample, y = Percentage, fill = Exclusion_Type)) +
  geom_col(
    position = position_dodge(width = 0.8),
    color = "black",
    linewidth = 0.2
  ) +
  
  scale_fill_manual(
    values = qc_colours,
    labels = c(
      "UMI↑" = TeX("UMI$\\uparrow$"),
      "UMI↓" = TeX("UMI$\\downarrow$"),
      "Genes↓" = TeX("Genes$\\downarrow$"),
      "Mito↑" = TeX("Mito$\\uparrow$"),
      "Haemo↑" = TeX("Haemo$\\uparrow$")
    )
  ) +
  
  add_axis_lines(105) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100), limits = c(0, 110)) +
  theme_thesis() +
  
  labs(
    x = "Sample",
    y = TeX("Percentage (%)"),
    title = "Percentage of cells meeting exclusion criteria in each sample"
  )

print(p)
```

```{r bar_qc, fig.width=6, fig.height=4}
p <- ggplot(qc_long, aes(x = Sample, y = Percentage, fill = Exclusion_Type)) +
  geom_col(
    position = position_dodge(width = 0.8),
    color = "black",
    linewidth = 0.2
  ) +
  
  scale_fill_manual(values = qc_colours) +
  add_axis_lines(105) +
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100), limits = c(0, 110)) +
  theme_thesis_simple() +  # ← Changed here
  
  labs(
    x = "Sample",
    y = "Percentage (%)",
    title = "Percentage of cells meeting exclusion criteria in each sample"
  )

print(p)
```


# Session info

```{r session info}
sessionInfo()
```
